### ISSUE TITLE
Fibocom L860 support and install procedure

### ISSUE THREAD

**Issue by marksdemellin** [karnadii/KarnadiWrt#6]
Hello, I have two questions about this project. How you interfaced Fibocom 4G module and the box?
Then, how to flash firmware to the box?
Thanks in advance.

**Comment by karnadii** [comment]
sorry for the late reply, for some reason I don't get the notification, You have to buy ngff b to usb 3 module, connect the module using usb extenter to the tv box, to flash it you just need to burn the image to sdcard then insert the sdcard to the tv box, press reset button of your tv box when booting
